# 53. Membuat kategori baru berdasarkan threshold (ambang batas)

# Import module

In [3]:
import pandas as pd

# Persiapan `DataFrame`

In [6]:
data = {
    "hobi":["jogging","mancing","berenang","mancing","mancing","membaca","membaca","mancing","fotografi","mancing","camping"]
}

df = pd.DataFrame(data)
df

         hobi
0     jogging
1     mancing
2    berenang
3     mancing
4     mancing
5     membaca
6     membaca
7     mancing
8   fotografi
9     mancing
10    camping

# Membuat kategori baru berdasarkan threshold (ambang batas)

In [9]:
df["hobi"].value_counts()

hobi
mancing      5
membaca      2
jogging      1
berenang     1
fotografi    1
camping      1
Name: count, dtype: int64

In [13]:
persentase = df["hobi"].value_counts(normalize=True)
persentase

hobi
mancing      0.454545
membaca      0.181818
jogging      0.090909
berenang     0.090909
fotografi    0.090909
camping      0.090909
Name: proportion, dtype: float64

In [15]:
threshold = 0.1
lainnya = persentase[persentase < threshold].index
lainnya

Index(['jogging', 'berenang', 'fotografi', 'camping'], dtype='object', name='hobi')

In [19]:
df["hobi"] = df["hobi"].replace(lainnya,"lainnya")
df

       hobi
0   lainnya
1   mancing
2   lainnya
3   mancing
4   mancing
5   membaca
6   membaca
7   mancing
8   lainnya
9   mancing
10  lainnya

In [21]:
df["hobi"].value_counts(normalize=True)

hobi
mancing    0.454545
lainnya    0.363636
membaca    0.181818
Name: proportion, dtype: float64