# 45. Memadukan `loc` dan `iloc` untuk melakukan seleksi data pada `DataFrame`

# Impprt module

In [4]:
import pandas as pd

# Persiapan `DataFrame`

In [6]:
df = pd.read_csv("../titanicfull.csv")
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S

In [7]:
df.iloc[15:20,2:5]

                                               name     sex   age
15                              Baumann, Mr. John D    male   NaN
16                         Baxter, Mr. Quigg Edmond    male  24.0
17  Baxter, Mrs. James (Helene DeLaudeniere Chaput)  female  50.0
18                            Bazzani, Miss. Albina  female  32.0
19                             Beattie, Mr. Thomson    male  36.0

In [8]:
df.loc[15:20,"name":"age"]

                                               name     sex   age
15                              Baumann, Mr. John D    male   NaN
16                         Baxter, Mr. Quigg Edmond    male  24.0
17  Baxter, Mrs. James (Helene DeLaudeniere Chaput)  female  50.0
18                            Bazzani, Miss. Albina  female  32.0
19                             Beattie, Mr. Thomson    male  36.0
20                    Beckwith, Mr. Richard Leonard    male  37.0