# 21. Agregasi pada Pandas Data Frame dengan agg

## Import module

In [4]:
import pandas as pd

## Persiapan `DataFrame`

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/boedybios/kaggle_explorations/master/Iris_Data_Classification_and_EDA/dataset/iris/Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## Mengenal `.groupby()` dan fungsi agregasi

In [27]:
df.groupby("Species")["PetalLengthCm"].count().to_frame()

                 PetalLengthCm
Species
Iris-setosa                 50
Iris-versicolor             50
Iris-virginica              50

In [25]:
df.groupby("Species")["PetalLengthCm"].median().to_frame()

                 PetalLengthCm
Species
Iris-setosa               1.50
Iris-versicolor           4.35
Iris-virginica            5.55

In [23]:
df.groupby("Species")["PetalLengthCm"].mean().to_frame()

                 PetalLengthCm
Species
Iris-setosa              1.464
Iris-versicolor          4.260
Iris-virginica           5.552

## Agregasi dengan `.agg()`

In [21]:
df.groupby("Species")["PetalLengthCm"].agg(["count","mean","median"])

                 count   mean  median
Species
Iris-setosa         50  1.464    1.50
Iris-versicolor     50  4.260    4.35
Iris-virginica      50  5.552    5.55

## Agregasi dengan `.describe()`

In [30]:
df.groupby("Species")["PetalLengthCm"].describe()

                 count   mean       std  min  25%   50%    75%  max
Species
Iris-setosa       50.0  1.464  0.173511  1.0  1.4  1.50  1.575  1.9
Iris-versicolor   50.0  4.260  0.469911  3.0  4.0  4.35  4.600  5.1
Iris-virginica    50.0  5.552  0.551895  4.5  5.1  5.55  5.875  6.9