# Parameter header dan rows pada `read_csv()` function

## Import module

In [4]:
import pandas as pd

## Persiapan `DataFrame`

In [6]:
df = pd.read_csv("../Iris-error.csv")
df.head()

    1            5.1           2.2            3.5           1.4   Iris-error
0  ID  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2   Iris-error
2   3            4.7           3.2            1.3           0.2   Iris-error
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
df = pd.read_csv("../Iris-error.csv",header=1,skiprows=[2,3])
df.head()

   ID  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   4            4.6           3.1            1.5           0.2  Iris-setosa
1   5            5.0           3.6            1.4           0.2  Iris-setosa
2   6            5.4           3.9            1.7           0.4  Iris-setosa
3   7            4.6           3.4            1.4           0.3  Iris-setosa
4   8            5.0           3.4            1.5           0.2  Iris-setosa