# 17. Resampling pada data deret waktu

In [5]:
import pandas as pd
import numpy as np

## Persiapan `DataFrame`

In [12]:
n_rows = 365 * 24
n_cols = 2
cols = ['col1','col2']

df = pd.DataFrame(np.random.randint(1,20,size=(n_rows,n_cols)),columns=cols)
df.index = pd.date_range('1/1/2000',periods=n_rows)

df

            col1  col2
2000-01-01    14    18
2000-01-02    18    16
2000-01-03    17    16
2000-01-04     2    17
2000-01-05    17     9
...          ...   ...
2023-12-21    18    17
2023-12-22    15     4
2023-12-23    14    17
2023-12-24    18     2
2023-12-25     5    19

[8760 rows x 2 columns]

## Resampling data dengan interval monthly

In [14]:
df.resample('M')['col1'].sum().to_frame()

            col1
2000-01-31   311
2000-02-29   327
2000-03-31   319
2000-04-30   308
2000-05-31   336
...          ...
2023-08-31   281
2023-09-30   281
2023-10-31   301
2023-11-30   315
2023-12-31   282

[288 rows x 1 columns]

## Resampling data dengan interval daily

In [18]:
df.resample('D')['col1'].sum().to_frame()

            col1
2000-01-01    14
2000-01-02    18
2000-01-03    17
2000-01-04     2
2000-01-05    17
...          ...
2023-12-21    18
2023-12-22    15
2023-12-23    14
2023-12-24    18
2023-12-25     5

[8760 rows x 1 columns]