# 41. Menerapkan agregasi pada sejumlah kolom dengan `agg()`

## Import module

In [4]:
import pandas as pd

pd.__version__

'2.2.2'

## Persiapan `DataFrame`

In [6]:
df = pd.read_csv("../titanicfull.csv")
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S

In [18]:
df["survived"] = df["survived"].astype("bool")
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,True,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
1,1,True,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
2,1,False,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
3,1,False,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
4,1,False,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S

## Menerapkan agregasi pada sejumlah kolom dengan `agg()`

In [9]:
df.groupby("pclass").agg({
    "pclass":"count",
    "age":["mean","max","min"],
    "survived":"mean"
})

       pclass        age              survived
        count       mean   max   min      mean
pclass
1         323  39.159930  80.0  0.92  0.619195
2         277  29.506705  70.0  0.67  0.429603
3         709  24.816367  74.0  0.17  0.255289

In [10]:
df.groupby("pclass").agg(n_pass=("pclass","count"),avg_age=("age","mean"),max_age=("age","max"),min_age=("age","min"),survival_rate=("survived","mean"))

        n_pass    avg_age  max_age  min_age  survival_rate
pclass
1          323  39.159930     80.0     0.92       0.619195
2          277  29.506705     70.0     0.67       0.429603
3          709  24.816367     74.0     0.17       0.255289