# 30. Akses nilai variabel dalam fungsi `query`

## Import module

In [6]:
import pandas as pd
import numpy as np

## Persiapan `DataFrame`

In [8]:
n_rows = 10
n_cols = 5
cols = list("ABCDE")

df = pd.DataFrame(np.random.randint(1,20,size=(n_rows,n_cols)),columns=cols)
df

    A   B   C   D   E
0  17   8  13   8  16
1  18   8   1   8  13
2   5  15   2  11  10
3  18   3  15  14   2
4  16  14   1  16  12
5   2  15   4   1  16
6   7   5  14  18   4
7  15  11  19   8   5
8   4   5  14  14  17
9   5   3  17  18   5

## Akses nilai variabel pada `query()`

In [13]:
df.query('A < 5')

   A   B   C   D   E
5  2  15   4   1  16
8  4   5  14  14  17

In [32]:
df.query("A < 5 and B > 10")

   A   B  C  D   E
5  2  15  4  1  16

In [28]:
rerata = df["A"].mean()
rerata

10.7

In [30]:
df.query("A > @rerata")

    A   B   C   D   E
0  17   8  13   8  16
1  18   8   1   8  13
3  18   3  15  14   2
4  16  14   1  16  12
7  15  11  19   8   5