# 49. Seleksi kolom dengan `f-string`

# Import module

In [3]:
import pandas as pd

# Persiapan `DataFrame`

In [6]:
df = pd.read_csv("../Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

# Seleksi kolom dengan `f-string`

In [11]:
df["SepalWidthCm"].to_frame().head()

   SepalWidthCm
0           3.5
1           3.0
2           3.2
3           3.1
4           3.6

In [13]:
part = "Sepal"

df[f"{part}WidthCm"].to_frame().head()

   SepalWidthCm
0           3.5
1           3.0
2           3.2
3           3.1
4           3.6

In [17]:
df[["PetalWidthCm","PetalLengthCm"]].head()

   PetalWidthCm  PetalLengthCm
0           0.2            1.4
1           0.2            1.4
2           0.2            1.3
3           0.2            1.5
4           0.2            1.4

In [19]:
part = "Petal"

df[[f"{part}WidthCm",f"{part}LengthCm"]].head()

   PetalWidthCm  PetalLengthCm
0           0.2            1.4
1           0.2            1.4
2           0.2            1.3
3           0.2            1.5
4           0.2            1.4