# 29. Random sampling pada pandas `DataFrame`

## Import module

In [5]:
import pandas as pd

pd.__version__

'2.2.2'

## Persiapan `DataFrame`

In [8]:
data = {
    "col_1":[1,2,3,4,5],
    "col_2":[10,20,30,40,50]
}

df = pd.DataFrame(data)
df

   col_1  col_2
0      1     10
1      2     20
2      3     30
3      4     40
4      5     50

## Random sampling with/without replacement

In [13]:
df.sample(n=4,replace=False,random_state=0)

   col_1  col_2
2      3     30
0      1     10
1      2     20
3      4     40

In [17]:
df.sample(n=4,replace=True,random_state=0)

   col_1  col_2
4      5     50
0      1     10
3      4     40
3      4     40