# 7. Menghapus missing values pada `DataFrame`

## Import packages

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../titanicfull.csv')
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S

In [4]:
df_backup = df.copy(deep=True)

## Menghapus (drop) setiap kolom yang mengandung missing values (`NaN`)

In [6]:
df = df.dropna(axis='columns')
df.head()

,pclass,survived,name,sex,sibsp,parch,ticket
0,1,1,"Allen, Miss. Elisabeth Walton",female,0,0,24160
1,1,1,"Allison, Master. Hudson Trevor",male,1,2,113781
2,1,0,"Allison, Miss. Helen Loraine",female,1,2,113781
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,1,2,113781
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,1,2,113781

## Menghapus (drop) setiap rows yang mengandung missing values (`NaN`)

In [7]:
df = df_backup

df = df.dropna(axis='rows')
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S

## Melihat presentase missng values (`NaN`) untuk setiap kolom

In [8]:
df = df_backup

df.isna().mean()

pclass      0.000000
survived    0.000000
name        0.000000
sex         0.000000
age         0.200917
sibsp       0.000000
parch       0.000000
ticket      0.000000
fare        0.000764
cabin       0.774637
embarked    0.001528
dtype: float64

## Menghapus (drop) missing values (`NaN`) untuk setiap kolom berdasarkan threshold

In [9]:
treshold = len(df) * 0.9
df = df.dropna(thresh=treshold,axis='columns')
df.head()

,pclass,survived,name,sex,sibsp,parch,ticket,fare,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,0,0,24160,211.3375,S
1,1,1,"Allison, Master. Hudson Trevor",male,1,2,113781,151.5500,S
2,1,0,"Allison, Miss. Helen Loraine",female,1,2,113781,151.5500,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,1,2,113781,151.5500,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,1,2,113781,151.5500,S