# 47. Deteksi dan penanganan kolom dengan tipe data beragam (mixed data types)

# Import module

In [3]:
import pandas as pd

# Persiapan `DataFrame`

In [6]:
data = {
    "Nama":["Bejo","Tejo","Wati","Tiwi","Cecep"],
    "Ipk":[2,"3",3,2.75,"3.25"]
}

df = pd.DataFrame(data)
df

    Nama   Ipk
0   Bejo     2
1   Tejo     3
2   Wati     3
3   Tiwi  2.75
4  Cecep  3.25

# Deteksi dan penanganan kolom dengan tipe data beragam (mixed data types)

In [10]:
df.dtypes

Nama    object
Ipk     object
dtype: object

In [20]:
df["Ipk"].apply(type)

0      <class 'int'>
1      <class 'str'>
2      <class 'int'>
3    <class 'float'>
4      <class 'str'>
Name: Ipk, dtype: object

In [22]:
df["Ipk"].apply(type).value_counts()

Ipk
<class 'int'>      2
<class 'str'>      2
<class 'float'>    1
Name: count, dtype: int64

In [24]:
df["Ipk"] = df["Ipk"].astype("float")

In [28]:
df["Ipk"].apply(type).value_counts()

Ipk
<class 'float'>    5
Name: count, dtype: int64

In [30]:
df

    Nama   Ipk
0   Bejo  2.00
1   Tejo  3.00
2   Wati  3.00
3   Tiwi  2.75
4  Cecep  3.25