# 46. Seleksi weekdays and weekends pada data deret waktu (time series)

# Import modules

In [5]:
import pandas as pd
import numpy as np

# Persiapan `DataFrame`

In [16]:
n_rows = 365
n_cols = 2
cols = ["col1","col2"]

df = pd.DataFrame(np.random.randint(1,20,size=(n_rows,n_cols)),columns=cols)

df.index = pd.date_range("2018-1-1",periods=n_rows,freq="D")
df

            col1  col2
2018-01-01    13     9
2018-01-02    15     6
2018-01-03    11     5
2018-01-04    17    10
2018-01-05    16     7
...          ...   ...
2018-12-27     3    15
2018-12-28     1    12
2018-12-29     1    16
2018-12-30     1    19
2018-12-31    11     2

[365 rows x 2 columns]

# Seleksi weekdays dan weekends

In [19]:
weekdays_df = df[df.index.dayofweek.isin([0,1,2,3,4])]
weekdays_df.head(7)

            col1  col2
2018-01-01    13     9
2018-01-02    15     6
2018-01-03    11     5
2018-01-04    17    10
2018-01-05    16     7
2018-01-08     1     1
2018-01-09    19     4

In [21]:
weekends_df = df[df.index.dayofweek.isin([5,6])]
weekends_df.head(7)

            col1  col2
2018-01-06     8    14
2018-01-07    13    10
2018-01-13     7    17
2018-01-14    16    12
2018-01-20    18     4
2018-01-21     1     6
2018-01-27    16    12