# 34. Mapping pada `DataFrame` menggunakan `applymap()`

## Import module

In [3]:
import pandas as pd

pd.__version__

'2.2.2'

## Persiapan `DataFrame`

In [5]:
data = {
    "jenis_kelamin":["pria","Wanita","lelaki","Lelaki","perempuan"],
    "usia":[21,22,23,24,25],
    "shift":["pagi","Siang","Malam","siang","pagi"]
}

df = pd.DataFrame(data)
df

  jenis_kelamin  usia  shift
0          pria    21   pagi
1        Wanita    22  Siang
2        lelaki    23  Malam
3        Lelaki    24  siang
4     perempuan    25   pagi

## Mapping pada `DataFrame` dengan `applymap()`

In [7]:
df = df.applymap(lambda x: x.lower() if type(x) == str else x)
df

C:\Users\ibnua\AppData\Local\Temp\ipykernel_10888\1270923860.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.lower() if type(x) == str else x)

  jenis_kelamin  usia  shift
0          pria    21   pagi
1        wanita    22  siang
2        lelaki    23  malam
3        lelaki    24  siang
4     perempuan    25   pagi

## `applymap()` dengan dictionary

In [17]:
mapping = {
    "pria":"L",
    "Lelaki":"L",
    "lelaki":"L",
    "wanita":"P",
    "perempuan":"P",
    "pagi":1,
    "siang":2,
    "malam":3
}

df.applymap(mapping.get)

C:\Users\ibnua\AppData\Local\Temp\ipykernel_10888\2943325206.py:12: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(mapping.get)

  jenis_kelamin  usia  shift
0             L  None      1
1             P  None      2
2             L  None      3
3             L  None      2
4             P  None      1

In [19]:
df[["jenis_kelamin","shift"]] = df[["jenis_kelamin","shift"]].applymap(mapping.get)
df

C:\Users\ibnua\AppData\Local\Temp\ipykernel_10888\4196328936.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[["jenis_kelamin","shift"]] = df[["jenis_kelamin","shift"]].applymap(mapping.get)

  jenis_kelamin  usia  shift
0             L    21      1
1             P    22      2
2             L    23      3
3             L    24      2
4             P    25      1