# 6. Mengganti nama kolom pada `DataFrame`

## Import packages

In [1]:
import pandas as pd

In [2]:
data = {
    'A':['Ali','Gerry','Mogi'],
    'B':[21,20,19]
}

df = pd.DataFrame(data)
df

       A   B
0    Ali  21
1  Gerry  20
2   Mogi  19

## Mengganti nama (label) untuk sebuah kolom pada `DataFrame`

In [3]:
df = df.rename(columns={'A':'Name'})
df

    Name   B
0    Ali  21
1  Gerry  20
2   Mogi  19

In [4]:
df = df.rename(columns={'B':'Age'})
df

    Name  Age
0    Ali   21
1  Gerry   20
2   Mogi   19