# 13. Konversi nilai numerik ke dalam kategori pada `DataFrame`

In [1]:
import pandas as pd
import numpy as np

## Persiapan `DataFrame`

In [2]:
n_rows = 10
n_cols = 1
cols = ('usia',)

df = pd.DataFrame(np.random.randint(1,70,size=(n_rows,n_cols)),columns=cols)
df

   usia
0    12
1    52
2    19
3    50
4    57
5    29
6    44
7    51
8    67
9     9

## Pengelompokan nilai numerik ke dalam beberapa kategori menggunakan `cut()`

In [4]:
df['kelompok_usia'] = pd.cut(df['usia'],bins=[0,18,40,70],labels=['anak','dewasa','manula'])
df

   usia kelompok_usia
0    12          anak
1    52        manula
2    19        dewasa
3    50        manula
4    57        manula
5    29        dewasa
6    44        manula
7    51        manula
8    67        manula
9     9          anak