# Meyatukan kolom dengan `str.cat()`

## Import module

In [3]:
import pandas as pd

pd.__version__

'2.2.2'

## Persiapan `DataFrame`

In [6]:
data = {
    "Nama":["Ali","Bayu","Indra","Devi"],
    "Jenis_kelamin":["L","L","L","P"],
    "Usia":[21,23,22,25]
}

df = pd.DataFrame(data)
df

    Nama Jenis_kelamin  Usia
0    Ali             L    21
1   Bayu             L    23
2  Indra             L    22
3   Devi             P    25

## Menyatukan kolom dengan `str.cat()`

In [9]:
df["Nama"].str.cat(df["Jenis_kelamin"],sep=", ").to_frame()

       Nama
0    Ali, L
1   Bayu, L
2  Indra, L
3   Devi, P

In [11]:
df["Nama_dan_Jenis_kelamin"] = df["Nama"].str.cat(df["Jenis_kelamin"],sep=", ")
df

    Nama Jenis_kelamin  Usia Nama_dan_Jenis_kelamin
0    Ali             L    21                 Ali, L
1   Bayu             L    23                Bayu, L
2  Indra             L    22               Indra, L
3   Devi             P    25                Devi, P

In [13]:
df["Nama"].str.cat(df["Usia"].astype("str"), sep=" - ").to_frame()

         Nama
0    Ali - 21
1   Bayu - 23
2  Indra - 22
3   Devi - 25

In [15]:
df["Nama_dan_Usia"] = df["Nama"].str.cat(df["Usia"].astype("str"), sep=" - ")
df

    Nama Jenis_kelamin  Usia Nama_dan_Jenis_kelamin Nama_dan_Usia
0    Ali             L    21                 Ali, L      Ali - 21
1   Bayu             L    23                Bayu, L     Bayu - 23
2  Indra             L    22               Indra, L    Indra - 22
3   Devi             P    25                Devi, P     Devi - 25