# 4. Pemilihan kolom (columns selection) pada Pandas `DataFrame` berdasarkan tipe data

## Import packages

In [1]:
import pandas as pd
import numpy as np

## Persiapan `DataFrame`

In [11]:
n_rows = 5
n_cols = 4
cols = ['bilangan_bulat','bilangan_pecahan','waktu','teks']

df = pd.DataFrame(np.random.randint(1,20,size=(n_rows,n_cols)),columns=cols)

df['waktu'] = pd.date_range('1/1/2000',periods=n_rows)
df['bilangan_pecahan'] = np.random.rand(n_rows)
df['teks'] = tuple('ABCDE')

df

   bilangan_bulat  bilangan_pecahan      waktu teks
0              14          0.347305 2000-01-01    A
1               2          0.061847 2000-01-02    B
2              12          0.539306 2000-01-03    C
3              11          0.188278 2000-01-04    D
4              16          0.256468 2000-01-05    E

In [12]:
df.dtypes

bilangan_bulat               int32
bilangan_pecahan           float64
waktu               datetime64[ns]
teks                        object
dtype: object

## Memilih kolom bertipe data numerik

In [13]:
df.select_dtypes(include='number')

   bilangan_bulat  bilangan_pecahan
0              14          0.347305
1               2          0.061847
2              12          0.539306
3              11          0.188278
4              16          0.256468

In [14]:
df.select_dtypes(include='float')

   bilangan_pecahan
0          0.347305
1          0.061847
2          0.539306
3          0.188278
4          0.256468

In [15]:
df.select_dtypes(include='int')

   bilangan_bulat
0              14
1               2
2              12
3              11
4              16

## Memilih kolom bertipe data datetime

In [16]:
df.select_dtypes(include='datetime')

       waktu
0 2000-01-01
1 2000-01-02
2 2000-01-03
3 2000-01-04
4 2000-01-05

## Memilih kolom bertipe data string atau `object`

In [17]:
df.select_dtypes(include='object')

  teks
0    A
1    B
2    C
3    D
4    E

## Memilih kolom dengan kombinasi tipe data

In [18]:
df.select_dtypes(include=['datetime','object'])

       waktu teks
0 2000-01-01    A
1 2000-01-02    B
2 2000-01-03    C
3 2000-01-04    D
4 2000-01-05    E