# 43. Menangani whitespace pada `DataFrame`

# Import modules

In [7]:
import pandas as pd
import numpy as np

# Persiapan `DataFrame`

In [10]:
data = {
    "nim":["10","11","12","13"," "],
    "nama":["Adi"," ","Tejo"," ","Bejo"]
}

df = pd.DataFrame(data)
df

  nim  nama
0  10   Adi
1  11
2  12  Tejo
3  13
4      Bejo

# Menangani whitespace pada `DataFrame`

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nim     5 non-null      object
 1   nama    5 non-null      object
dtypes: object(2)
memory usage: 212.0+ bytes

In [15]:
df = df.replace(r"^\s*$",np.nan,regex=True)
df

   nim  nama
0   10   Adi
1   11   NaN
2   12  Tejo
3   13   NaN
4  NaN  Bejo

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nim     4 non-null      object
 1   nama    3 non-null      object
dtypes: object(2)
memory usage: 212.0+ bytes