# 54. Menyimpan `DataFrame` sebagai file `CSV`

# Import module

In [4]:
import pandas as pd

# Persiapan `DataFrame`

In [7]:
data = {
    "Nama":["Bayu","Indra","Devi","Agni"],
    "Jenis_kelamin":["L","L","P","L"],
    "Usia":[23,21,22,25]
}

df = pd.DataFrame(data)
df

    Nama Jenis_kelamin  Usia
0   Bayu             L    23
1  Indra             L    21
2   Devi             P    22
3   Agni             L    25

# Menyimpan `DataFrame` sebagai file `csv`

In [12]:
df.to_csv("data_peserta1.csv")

In [14]:
df = pd.read_csv("data_peserta1.csv")
df

   Unnamed: 0   Nama Jenis_kelamin  Usia
0           0   Bayu             L    23
1           1  Indra             L    21
2           2   Devi             P    22
3           3   Agni             L    25

In [16]:
df = pd.read_csv("data_peserta1.csv",index_col=0)
df

    Nama Jenis_kelamin  Usia
0   Bayu             L    23
1  Indra             L    21
2   Devi             P    22
3   Agni             L    25

In [22]:
df.to_csv("data_peserta2.csv",index=False)

In [24]:
df = pd.read_csv("data_peserta2.csv")
df

    Nama Jenis_kelamin  Usia
0   Bayu             L    23
1  Indra             L    21
2   Devi             P    22
3   Agni             L    25